### ISSUE TITLE
Movement speed of the monster

### ISSUE THREAD

**Issue by JenniferXX443** [Jennifer12659/groupproject-team2-coders-19#2]
I noticed that our monsters move too slowly and feel that the difficulty of this game is not challenging. It would be better to speed up the movement speed of the monsters.

**Comment by onzfonz** [comment]
For testing purposes, I would like you to add a button that will change the speed of the monsters in 1 unit increments for 5 different values. The speed should be  markedly different in at least 3 of the 5 values and should be stored as a number.
